num_1 = int(input("Enter the first number: "))
num_2 = int(input("Enter the second number: "))

print("Addition: ", num_1 + num_2)
print("Subtraction: ", num_1 - num_2)
print("Multiplication: ", num_1 * num_2)
print("Division: ", num_1 / num_2)
print("Modulus: ", num_1 % num_2)
print("Integer Division: ", num_1 // num_2)
print("Exponent: ", num_1 ** num_2)
